### ISSUE TITLE
Undefined symbols for architecture arm64 : _GADGetStringFromVersionNumber

### ISSUE THREAD

**Issue by cederache** [Ogury/ogury-cocoapods-repository#3]
Hi,
I'm using this pod in an iOS project but I have this issue since I upgrade this pod from 4.2.3 to 4.3.0 :

```
Undefined symbols for architecture arm64:
  "_GADGetStringFromVersionNumber", referenced from:
      +[OGGMediationVersion sdkVersion] in OguryMediationGoogleMobileAds[3](OGGMediationVersion.o)
      +[OguryCustomEventsShared startWithAssetKey:] in OguryMediationGoogleMobileAds[9](OguryCustomEventsShared-4bb5ea0333947c0c185ce0932dac59a1.o)
ld: symbol(s) not found for architecture arm64
```

I'm building the project on Xcode 15.4 and targeting iOS version  >= 15.0

I also tried the 4.4.0 version but I have the same bug

**Comment by cederache** [comment]
Après d'autres tests, il semblerait qu'il faille que je mette à jour manuellement le GoogleMobileAds en version >= 11
